from enum import Enum, auto

class HealthState(Enum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    RECOVERING = "RECOVERING"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"

class Subsystem(Enum):
    KOTAK_NEO_AUTH = "KOTAK_NEO_AUTH"
    REST_API = "REST_API"
    WEBSOCKET = "WEBSOCKET"
    MARKET_DATA = "MARKET_DATA"
    OPTION_CHAIN = "OPTION_CHAIN"
    NIFTY_50 = "NIFTY_50"
    PCR_PIPELINE = "PCR_PIPELINE"
    OI_PIPELINE = "OI_PIPELINE"
    FRONTEND_BACKEND = "FRONTEND_BACKEND"
    BACKGROUND_WORKER = "BACKGROUND_WORKER"
    TIMER = "TIMER"
    SYSTEM_RESOURCES = "SYSTEM_RESOURCES"
    STATE = "STATE"
    UNKNOWN = "UNKNOWN"

class FailureCategory(Enum):
    NETWORK = "NETWORK"
    BROKER_CONNECTION = "BROKER_CONNECTION"
    AUTHENTICATION = "AUTHENTICATION"
    WEBSOCKET = "WEBSOCKET"
    API = "API"
    DATA = "DATA"
    CALCULATION = "CALCULATION"
    STATE = "STATE"
    FRONTEND = "FRONTEND"
    BACKEND = "BACKEND"
    RESOURCE = "RESOURCE"
    CONFIGURATION = "CONFIGURATION"
    UNKNOWN = "UNKNOWN"

class RecoveryLevel(Enum):
    LEVEL_1 = "RETRY"
    LEVEL_2 = "REINITIALIZE"
    LEVEL_3 = "RECONNECT"
    LEVEL_4 = "REBUILD"
    LEVEL_5 = "RESTART_WORKER"
    LEVEL_6 = "SAFE_RESTART"
